name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Upload files to Azure Blob Storage
      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch --destination ${{ secrets.AZURE_CONTAINER_NAME }} \
            --source . \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} \
            --overwrite
