name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} \
            --destination ${{ secrets.AZURE_CONTAINER_NAME }} --source ./cloud-resume \
            --source .
