name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to Azure Blob Storage
        uses: azure/azure-storage-blob-upload@v1
        with:
          account-name: ${{ secrets.azure_storage_account_name }}
          account-key: ${{ secrets.azure_storage_access_key }}
          container-name: ${{ secrets.AZURE_CONTAINER_NAME }}  # Keep this if you're using this secret for container name
          source: './'  # Current directory
          destination: '/'  # Root of the container
